version: '3'

services:

  haar:
    build:
      context:  ./haar
      dockerfile: Dockerfile
      #args:
        #- PYTHON_VERSION=3.7.0-alpine3.8

    ports:
      - 8098:8098
    stdin_open: true
    tty: true
    networks:
      - iotnet

  bot:
    build:
      context:  ./Telegram_Bot
      dockerfile: Dockerfile
      #args:
        #- PYTHON_VERSION=3.7.0-alpine3.8

    ports:
      - 8099:8099
    stdin_open: true
    tty: true
    networks:
      - iotnet


  control:
    build:
      context:  ./control
      dockerfile: Dockerfile
      #args:
        #- PYTHON_VERSION=3.7-slim-stretch
    ports:
      - 8090:8090
    stdin_open: true
    tty: true
    networks:
      - iotnet


  rc:
    build:
      context:  ./resource_catalog
      dockerfile: Dockerfile
      #args:
      #  - PYTHON_VERSION=3.7.0-alpine3.8
    ports:
      - 8087:8087
    stdin_open: true
    tty: true
    networks:
      - iotnet

networks:
  iotnet:


