ARG PYTHON_VERSION
FROM python:$PYTHON_VERSION
COPY . /app
WORKDIR /app
RUN pip install cherrypy
RUN pip install requests
RUN dpkg --print-architecture

# Install OpenCV's runtime dependencies
#RUN apt-get update
RUN apt-get -y install libglib2.0-0

# Install OpenCV headless using pip
RUN pip install opencv-python-headless==4.1.0.25

RUN python -c 'import cv2'
CMD python ./im_cap.py